GET http://localhost:3000/members

###

GET http://localhost:3000/members/Oscar Jacobsson

###

POST http://localhost:3000/members/
Content-Type: application/json

{   "name": "Sanna Andersson",
    "street": "Landvägen 38",
    "city": "Göteborg",
    "mobile": "0707444444"
  }

###

PUT http://localhost:3000/members/Sanna Andersson
Content-Type: application/json

{
    "name": "Sanna Andersson",
    "street": "Fabriksgatan 45",
    "city": "Mölndal",
    "mobile": "0707444444"
}


###

DELETE http://localhost:3000/members/Sanna Andersson
Content-Type: application/json


{}


